apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: hello
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World!"
		
		
		
		
		
kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
kubectl get namespaces
kubectl get pods -n tekton-pipelines
curl -LO https://github.com/tektoncd/cli/releases/download/v0.11.0/tkn_0.11.0_Linux_x86_64.tar.gz
tar xvzf tkn_0.11.0_Linux_x86_64.tar.gz -C /usr/local/bin/ tkn
write task-hello.yaml
kubectl apply -f task-hello.yaml
tkn task start hello --dry-run > taskRun-hello.yaml
kubectl create -f taskRun-hello.yaml
tkn taskrun logs --last -f 